[[package]] # the double square brackets define a TOML table array
name = "ton_lib"
changelog_path = "ton_lib/CHANGELOG.md"

[[package]] # the double square brackets define a TOML table array
name = "ton_lib_macros"
changelog_path = "ton_lib_macros/CHANGELOG.md"

