[workspace]
resolver = "2"
members = [
    "ton_lib",
    "ton_lib_macros",
]

[workspace.package]
description = "A collection of types and utilities for interacting with the TON network"
keywords = ["ton", "the-open-network", "blockchain", "crypto"]
edition = "2021"
authors = ["Sild <silddev@icloud.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sild/ton_lib_rs"
rust-version = "1.81"
readme = "README.md"
publish = false


include = [
    "../resources/**",
]


[profile.bench]
debug = true
[profile.release]
debug = true
