[workspace]
members = [
    "src/auto_pool"
]

resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Sild <silddev@proton.me"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sild/libs_rs"
rust-version = "1.80"
publish = false
