[workspace]
members = [
    "auto_pool",
    "ton_lib",
    "ton_lib_proc_macro",
]

resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Sild <silddev@pm.me"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sild/libs_rs"
rust-version = "1.81"
publish = false

[profile.bench]
debug = true
[profile.release]
debug = true
