[package]
name = "ton_lib"
version = "0.0.1"
description = "Banch of tools for working with TON network"
keywords = ["ton", "the-open-network", "blockchain", "crypto"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]


[dev-dependencies]
