[package]
name = "ton_lib"
version = "0.0.3"
description = "A collection of types and utilities for interacting with the TON network"
keywords = ["ton", "the-open-network", "blockchain", "crypto"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = true

[features]
num-bigint = ["dep:num-bigint"]
fastnum = ["dep:fastnum"]

[dependencies]
# Internal
ton_lib_proc_macro = { path = "../ton_lib_proc_macro" }

bitstream-io = "2.6"
thiserror = "2.0"
log = "0.4"
sha2 = {version = "0.10"}
crc = "3.2.1"
hex = "0.4.3"
base64 = "0.22"
fastnum = { version = "0.2", optional = true }
num-bigint = { version = "0.4", optional = true }
num-traits = { version = "0.2.19" }

[dev-dependencies]
ton_lib = { path = ".", features = ["num-bigint", "fastnum"] }
anyhow = "1.0"
tokio-test = "0.4"
tonlib-core = "0.24.2"
criterion = "0.5"
sha2 = {version = "0.10", features = ["asm"]} # strongly recommend to enable it for your application
hex = "0.4.3"
colog = "1.3.0"

[[bench]]
name = "boc_to_from_bytes"
harness = false

[[bench]]
name = "build_cell"
harness = false
