[package]
name = "example"
authors = ["Sild <sildtm@icloud.com>"]
repository = "https://github.com/Sild/async-autoreturn-pool"
version = "0.0.1"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "example"
path = "src/main.rs"

[[benchmark]]

[dependencies]
anyhow = "1.0.87"
autoreturn-pool = { path = "../library" }
