[package]
name = "autoreturn-pool"
edition.workspace = true
rust-version.workspace = true
publish = true
version.workspace = true
description.workspace = true
license.workspace = true
readme = "../../README.md"

[dependencies]
log.workspace = true
parking_lot.workspace = true

[dev-dependencies]
anyhow.workspace = true
