[package]
name = "autoreturn_pool"
edition.workspace = true
rust-version.workspace = true
publish = true
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
log.workspace = true

[dev-dependencies]
anyhow.workspace = true
