[package]
name = "autoreturn-pool"
edition.workspace = true
rust-version.workspace = true
publish = true
version.workspace = true
description.workspace = true
license.workspace = true
readme = "../../README.md"

[dependencies]
parking_lot = "0.12"

[dev-dependencies]
criterion = { version = "0.5" }
lockfree-object-pool = "0.1.6"
object-pool = "0.6.0"

[[bench]]
name = "benchmark"
harness = false