[package]
name = "autoreturn-pool"
edition.workspace = true
rust-version.workspace = true
publish = true
version.workspace = true
description.workspace = true
license.workspace = true
readme = "../../README.md"

[dependencies]
parking_lot.workspace = true

[dev-dependencies]
criterion.workspace = true
lockfree-object-pool.workspace = true
object-pool.workspace = true

[[bench]]
name = "benchmark"
harness = false