name: Build-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install nightly
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libsecp256k1-dev liblz4-dev
    - run: cargo +nightly fmt --check
    - run: cargo build --all-features --verbose
    - run: cargo test --all
    - run: cargo test --all --all-features
