name: Release

on:
  workflow_dispatch:
    inputs:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: release-plz
        uses: MarcoIeni/release-plz-action@v0.5.65
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.CRATES_IO_REGISTRY_TOKEN }}
          config: ".release-plz.toml"
