[package]
name = "ton_lib_proc_macro"
version = "0.0.1"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1"
deluxe = "0.5.0"

[lib]
proc-macro = true
